import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6">
          <Link href="/">
            <Button variant="ghost" size="sm" data-testid="link-back-home">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>
        
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl sm:text-3xl">Terms of Service</CardTitle>
            <p className="text-sm text-muted-foreground">Last Updated: January 2025</p>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
              <p className="text-muted-foreground">
                Welcome to FairSign ("we," "our," or "us"), a service provided by Lannisport Limited. 
                By accessing or using our website, API, or mobile applications (collectively, the "Service"), 
                you agree to be bound by these Terms of Service ("Terms").
              </p>
              <p className="text-muted-foreground">
                If you do not agree to these Terms, you may not access or use the Service.
              </p>
              <div className="mt-4 p-4 bg-muted rounded-md">
                <h3 className="font-medium mb-2">Company Information:</h3>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li><strong>Name:</strong> Lannisport Limited</li>
                  <li><strong>Registered Address:</strong> 4th Floor, Phibsborough Tower, Dublin, D07 XH2D, Republic of Ireland</li>
                  <li><strong>Phone:</strong> 018273662</li>
                  <li><strong>Contact Email:</strong> support@fairsign.io</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. Definitions</h2>
              <ul className="text-muted-foreground space-y-2">
                <li><strong>"User" or "You"</strong> means any individual or entity that registers an account or uses the Service.</li>
                <li><strong>"Customer Data"</strong> means electronic documents, contracts, and signature data uploaded or generated by you through the Service.</li>
                <li><strong>"Signer"</strong> means a third party to whom you send documents for signature via the Service.</li>
                <li><strong>"Service"</strong> means the FairSign electronic signature platform, including Free and Enterprise tiers.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. Account Registration</h2>
              <p className="text-muted-foreground">
                <strong>3.1. Eligibility:</strong> You must be at least 18 years old to use the Service. By creating an account, 
                you represent that you have the legal capacity to enter into a binding contract.
              </p>
              <p className="text-muted-foreground">
                <strong>3.2. Security:</strong> You are responsible for maintaining the confidentiality of your login credentials 
                (email, password, and 2FA tokens). You are fully responsible for all activities that occur under your account.
              </p>
              <p className="text-muted-foreground">
                <strong>3.3. Accuracy:</strong> You agree to provide accurate, current, and complete information during registration 
                and to update such information to keep it accurate, current, and complete.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. Data Protection and GDPR</h2>
              <p className="text-muted-foreground mb-3">
                Since we operate in the Republic of Ireland, we are fully committed to compliance with the 
                General Data Protection Regulation (EU) 2016/679 ("GDPR").
              </p>
              <p className="text-muted-foreground">
                <strong>4.1. Our Role as Controller:</strong> For your account data (name, email, billing details, login credentials), 
                Lannisport Limited acts as the Data Controller. We process this data to provide the Service, manage your account, 
                and comply with legal obligations.
              </p>
              <p className="text-muted-foreground">
                <strong>4.2. Our Role as Processor:</strong> For the contents of the documents you upload and the data of the Signers 
                you invite, you are the Data Controller, and we act as the Data Processor. We process this data solely on your 
                instructions to facilitate the signing process.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Electronic Signatures and Legal Validity</h2>
              <p className="text-muted-foreground">
                <strong>5.1. eIDAS Regulation:</strong> FairSign provides electronic signatures designed to comply with 
                Regulation (EU) No 910/2014 (eIDAS).
              </p>
              <p className="text-muted-foreground">
                <strong>5.2. No Legal Advice:</strong> We provide a technological platform for the execution of documents. 
                We do not provide legal advice regarding the validity of any specific contract or document in your specific jurisdiction. 
                It is your responsibility to ensure that the use of electronic signatures is valid for your specific use case.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. Acceptable Use Policy</h2>
              <p className="text-muted-foreground mb-2">You agree not to use the Service to:</p>
              <ul className="text-muted-foreground space-y-1 list-disc list-inside">
                <li>6.1. Upload documents containing illegal, offensive, or fraudulent content.</li>
                <li>6.2. Send unsolicited emails (spam) to Signers.</li>
                <li>6.3. Attempt to reverse engineer, decompile, or hack the Service.</li>
                <li>6.4. Impersonate any person or entity or falsely state your affiliation with a person or entity.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. Subscription, Fees, and Payment</h2>
              <p className="text-muted-foreground">
                <strong>7.1. Free Tier:</strong> We may offer a free version of the Service with limited features. 
                We reserve the right to modify the limits of the Free Tier at any time.
              </p>
              <p className="text-muted-foreground">
                <strong>7.2. Enterprise/Pro Tiers:</strong> Paid subscriptions are billed in advance on a monthly or annual basis. 
                You agree to provide valid payment information.
              </p>
              <p className="text-muted-foreground">
                <strong>7.3. Taxes:</strong> Prices quoted are exclusive of VAT unless otherwise stated. If you are located in the EU, 
                VAT will be applied at the applicable Irish rate unless you provide a valid VAT number.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Intellectual Property</h2>
              <p className="text-muted-foreground">
                <strong>8.1. Our IP:</strong> Lannisport Limited retains all rights, title, and interest in and to the 
                FairSign platform, including source code, designs, logos, and software.
              </p>
              <p className="text-muted-foreground">
                <strong>8.2. Your IP:</strong> You retain all rights and ownership of the Customer Data (documents) you upload. 
                We claim no ownership over your contracts. You grant us a limited license to store and process these documents 
                solely for the purpose of providing the Service to you.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">9. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                <strong>9.1.</strong> To the maximum extent permitted by applicable law, Lannisport Limited shall not be 
                liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, 
                whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses.
              </p>
              <p className="text-muted-foreground">
                <strong>9.2.</strong> Our total liability for any claim arising out of or relating to these Terms or the Service 
                shall not exceed the amount you paid us for the Service in the twelve (12) months prior to the event giving rise to the claim.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">10. Termination</h2>
              <p className="text-muted-foreground">
                We may suspend or terminate your access to the Service immediately, without prior notice or liability, if you breach 
                these Terms. Upon termination, your right to use the Service will cease immediately. You will be provided a reasonable 
                window to export your signed documents unless the termination is due to a security breach or illegal activity.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">11. Governing Law and Dispute Resolution</h2>
              <p className="text-muted-foreground">
                <strong>11.1.</strong> These Terms shall be governed by and construed in accordance with the laws of the 
                Republic of Ireland, without regard to its conflict of law provisions.
              </p>
              <p className="text-muted-foreground">
                <strong>11.2.</strong> Any dispute arising out of or in connection with these Terms shall be subject to the 
                exclusive jurisdiction of the courts of Dublin, Ireland.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">12. Contact Us</h2>
              <p className="text-muted-foreground mb-2">If you have any questions about these Terms, please contact us:</p>
              <ul className="text-muted-foreground space-y-1">
                <li><strong>By Post:</strong> Lannisport Limited, 4th Floor, Phibsborough Tower, Dublin, D07 XH2D</li>
                <li><strong>By Phone:</strong> 018273662</li>
                <li><strong>By Email:</strong> support@fairsign.io</li>
              </ul>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
